[mgr]
cwd = { fg = "#c4c3c9" }
hovered = { fg = "#161027", bg = "#c4c3c9" }
find_keyword = { fg = "#C0BFC5", italic = true }
find_position = { fg = "#c4c3c9", bold = true, italic = true }
marker_copied = { fg = "#161027", bg = "#C0BFC5" }
marker_cut = { fg = "#161027", bg = "#896C9C" }
marker_marked = { fg = "#161027", bg = "#8776AB" }
marker_selected = { fg = "#161027", bg = "#A795D3" }
tab_active = { fg = "#161027", bg = "#c4c3c9" }
tab_inactive = { fg = "#896C9C", bg = "#655f75" }
count_copied = { fg = "#161027", bg = "#C0BFC5" }
count_cut = { fg = "#161027", bg = "#896C9C" }
count_selected = { fg = "#161027", bg = "#A795D3" }
border_fg = "#A795D3"

[status]
mode_normal = { fg = "#161027", bg = "#c4c3c9", bold = true }
mode_select = { fg = "#161027", bg = "#8776AB", bold = true }
mode_unset = { fg = "#161027", bg = "#896C9C", bold = true }
progress_fg = "#c4c3c9"
progress_bg = "#655f75"
progress_error = { fg = "#896C9C", bg = "#161027" }
permissions_t = "#c4c3c9"
permissions_r = "#C0BFC5"
permissions_w = "#896C9C"
permissions_x = "#8776AB"
permissions_s = "#A795D3"

[input]
border = "#A795D3"
selected = { fg = "#161027", bg = "#c4c3c9" }

[select]
border = "#A795D3"
active = "#c4c3c9"

[tasks]
border = "#A795D3"

[which]
mask_bg = "#655f75"
cand = "#c4c3c9"
rest = "#c4c3c9"
desc = "#C0BFC5"

[notify]
title_info = "#c4c3c9"
title_warn = "#C0BFC5"
title_error = "#896C9C"

[filetype]
rules = [
  { mime = "image/*", fg = "#C0BFC5" },
  { mime = "video/*", fg = "#C0BFC5" },
  { mime = "audio/*", fg = "#C0BFC5" },
  { mime = "application/zip", fg = "#896C9C" },
  { mime = "application/x-tar", fg = "#896C9C" },
  { mime = "application/x-bzip2", fg = "#896C9C" },
  { mime = "application/x-7z-compressed", fg = "#896C9C" },
  { mime = "application/x-rar", fg = "#896C9C" },
  { mime = "text/*", fg = "#c4c3c9" },
  { mime = "application/json", fg = "#8776AB" },
  { mime = "*/", fg = "#c4c3c9" },
]
