[mgr]
cwd = { fg = "#c5c6c8" }
hovered = { fg = "#191c24", bg = "#c5c6c8" }
find_keyword = { fg = "#DBC7A5", italic = true }
find_position = { fg = "#c5c6c8", bold = true, italic = true }
marker_copied = { fg = "#191c24", bg = "#DBC7A5" }
marker_cut = { fg = "#191c24", bg = "#6F7587" }
marker_marked = { fg = "#191c24", bg = "#798C8F" }
marker_selected = { fg = "#191c24", bg = "#D1BAAA" }
tab_active = { fg = "#191c24", bg = "#c5c6c8" }
tab_inactive = { fg = "#6F7587", bg = "#616777" }
count_copied = { fg = "#191c24", bg = "#DBC7A5" }
count_cut = { fg = "#191c24", bg = "#6F7587" }
count_selected = { fg = "#191c24", bg = "#D1BAAA" }
border_fg = "#D1BAAA"

[status]
mode_normal = { fg = "#191c24", bg = "#c5c6c8", bold = true }
mode_select = { fg = "#191c24", bg = "#798C8F", bold = true }
mode_unset = { fg = "#191c24", bg = "#6F7587", bold = true }
progress_fg = "#c5c6c8"
progress_bg = "#616777"
progress_error = { fg = "#6F7587", bg = "#191c24" }
permissions_t = "#c5c6c8"
permissions_r = "#DBC7A5"
permissions_w = "#6F7587"
permissions_x = "#798C8F"
permissions_s = "#D1BAAA"

[input]
border = "#D1BAAA"
selected = { fg = "#191c24", bg = "#c5c6c8" }

[select]
border = "#D1BAAA"
active = "#c5c6c8"

[tasks]
border = "#D1BAAA"

[which]
mask_bg = "#616777"
cand = "#c5c6c8"
rest = "#c5c6c8"
desc = "#DBC7A5"

[notify]
title_info = "#c5c6c8"
title_warn = "#DBC7A5"
title_error = "#6F7587"

[filetype]
rules = [
  { mime = "image/*", fg = "#DBC7A5" },
  { mime = "video/*", fg = "#DBC7A5" },
  { mime = "audio/*", fg = "#DBC7A5" },
  { mime = "application/zip", fg = "#6F7587" },
  { mime = "application/x-tar", fg = "#6F7587" },
  { mime = "application/x-bzip2", fg = "#6F7587" },
  { mime = "application/x-7z-compressed", fg = "#6F7587" },
  { mime = "application/x-rar", fg = "#6F7587" },
  { mime = "text/*", fg = "#c5c6c8" },
  { mime = "application/json", fg = "#798C8F" },
  { mime = "*/", fg = "#c5c6c8" },
]
